# Generated by Django 5.0.6 on 2024-06-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('History', models.TextField()),
                ('date_added', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Histories',
            },
        ),
    ]
